### ISSUE TITLE
Create frames and encode to file (mp4)

### ISSUE THREAD

**Issue by ShockWave2048** [mysteryx93/HanumanInstitute.FFmpeg#2]
Hi mysteryx93!
Is it have example (or way) how render frames, and encode to stream?
Frames are with gradients, texts, bitmaps.
Thanks for answer!

**Comment by mysteryx93** [comment]
If you want to render frames dynamically, you may want to look into Avisynth which allows that, then encode the Avisynth script via Ffmpeg

Sent from ProtonMail mobile

-------- Original Message --------
