### ISSUE TITLE
Convert to gif and compress video

### ISSUE THREAD

**Issue by anomal3** [mysteryx93/HanumanInstitute.FFmpeg#4]
Hello my dear friend.
I can't find any information on how to compress or convert video to GIF. Is there a tutorial for my questions?

**Comment by mysteryx93** [comment]
This is a question entirely related to FFMPEG, you can search the internet, go through their [documentation](https://ffmpeg.org/documentation.html) or ask on a FFMPEG forum.

If you know the FFMPEG command-line syntax, then I can help you with the right C# syntax.
