### ISSUE TITLE
How to run avisynth script

### ISSUE THREAD

**Issue by zydjohnHotmail** [mysteryx93/HanumanInstitute.FFmpeg#5]
Hello:
I can run avisynth script like this:
C:\Videos\Test>type Version.avs
version()
C:\Videos\Test>VirtualDub64 Version.avs
Let me know how I can do this with the repo?
Thanks,

**Comment by mysteryx93** [comment]
There's no command-line arguments supported for now. It will also take a while before I'm ready to publish an update.
